<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                            "报表"
                        ],
                        "menu":"住户管理",
                        "menuJump":"列表",
                        "tableName":"zhuhu"
                    }
                ],
                "menu":"住户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"工作人员管理",
                        "menuJump":"列表",
                        "tableName":"gongzuo"
                    }
                ],
                "menu":"工作人员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "导出",
                            "删除"
                        ],
                        "menu":"核酸检测管理",
                        "menuJump":"列表",
                        "tableName":"jiance"
                    }
                ],
                "menu":"核酸检测管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "导出",
                            "删除"
                        ],
                        "menu":"隔离监控管理",
                        "menuJump":"列表",
                        "tableName":"geli"
                    }
                ],
                "menu":"隔离监控管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "导出",
                            "删除"
                        ],
                        "menu":"疫情上报管理",
                        "menuJump":"列表",
                        "tableName":"shangbao"
                    }
                ],
                "menu":"疫情上报管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"出入登记管理",
                        "menuJump":"列表",
                        "tableName":"dengji"
                    }
                ],
                "menu":"出入登记管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"来访登记管理",
                        "menuJump":"列表",
                        "tableName":"laifang"
                    }
                ],
                "menu":"来访登记管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"职务类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhiwu"
                    }
                    ,{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }

                ],
                "menu":"基础数据管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"住户管理",
                        "menuJump":"列表",
                        "tableName":"zhuhu"
                    }
                ],
                "menu":"住户管理"
            }
			,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"核酸检测管理",
                        "menuJump":"列表",
                        "tableName":"jiance"
                    }
                ],
                "menu":"核酸检测管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"隔离监控管理",
                        "menuJump":"列表",
                        "tableName":"geli"
                    }
                ],
                "menu":"隔离监控管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"疫情上报管理",
                        "menuJump":"列表",
                        "tableName":"shangbao"
                    }
                ],
                "menu":"疫情上报管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"出入登记管理",
                        "menuJump":"列表",
                        "tableName":"dengji"
                    }
                ],
                "menu":"出入登记管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"来访登记管理",
                        "menuJump":"列表",
                        "tableName":"laifang"
                    }
                ],
                "menu":"来访登记管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"工作人员",
        "tableName":"gongzuo"
    }
	,
	{
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"核酸检测管理",
                        "menuJump":"列表",
                        "tableName":"jiance"
                    }
                ],
                "menu":"核酸检测管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"出入登记管理",
                        "menuJump":"列表",
                        "tableName":"dengji"
                    }
                ],
                "menu":"出入登记管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"来访登记管理",
                        "menuJump":"列表",
                        "tableName":"laifang"
                    }
                ],
                "menu":"来访登记管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"住户",
        "tableName":"zhuhu"
    }
];

var hasMessage = '';
